# Author: Xiaotong Liu (liux4215@umn.edu)
# This script is to generate the second part of figure 2 for the manuscript
# The first part of figure 2 is the MCM structure generated by the ppt slides
# The plots are heatmaps.
# Most genes were fit with classical MCMs, some were fit with altered MCMs


# loading the libraries
library(ComplexHeatmap) # heatmap package
library(circlize)       # supporting package 
library(RColorBrewer)   # supporting package, for colors
library(grid)           # supporting package, for merging multiple heatmaps in a page
library(gridExtra)      # same above

# directory of MCM project, /MCM_paper/code_data.220329

rm(list=ls())
#### load data
load("./data/MCM.heatm.info.RData")  # 1889 consistently modeled upregulated genes
load("./data/glm_fixef_Ken_WT_with_pseudocounts.Rdata")  # 18442 genes

### genes with altered models and with original models
genes.alter.MCM = sort(c(genes_to_be_fixed, a.alter.genes))
genes.ori.MCM = setdiff(names(MCM.val.attp), genes.alter.MCM)

### matrices for the MCM, first-peak, second-peak values, gene x time
mat.MCM = t(sapply(MCM.val.attp, function(x) x['MCM',]))
mat.first = t(sapply(MCM.val.attp, function(x) x['First',]))
mat.second = t(sapply(MCM.val.attp, function(x) x['Second',]))

### glm mean estimates for 1939 genes x AvrRpt2 4-24h
glm.est = t(sapply(glm_fixef[names(MCM.val.attp)], function(x) x[,'Estimate']))
c.names = colnames(glm.est)
c.names = c.names[grep('AvrRpt2', c.names)]
c.names = c.names[4:10]  # 4h to 24h time points
glm.est1 = glm.est[,c.names]
## subtract mock
mat.mock = t(sapply(MCM.val.attp, function(x) x['mock',]))
glm.est1 = glm.est1 - mat.mock
colnames(glm.est1) = colnames(mat.mock)

### discrepancy glm - MCM
mat.disc = glm.est1 - mat.MCM
hist(mat.disc, breaks=25)
# very good, small abs and symmetric

###clustering based on the mat.MCM
dist_mat.not.fixed = dist(mat.MCM[genes.ori.MCM,])
mhclust.not.fixed = hclust(dist_mat.not.fixed,method = "average")
dist_mat.fixed = dist(mat.MCM[genes.alter.MCM,])
mhclust.fixed = hclust(dist_mat.fixed,method = "average")

# color scale
col = colorRamp2(c(-2, 0, 1, 2, 6), c("cornflowerblue","white","orange",'orangered',"red4"))
# annotations, for columns to show the time points
bot.anno = HeatmapAnnotation(foo = anno_text(colnames(glm.est1), rot = 0, 
                                             just = 'center',gp = gpar(fontsize = 11), location = unit(1,'mm')),
                             show_annotation_name = F)
#mean estimate heatmaps
ht.mean.estimate.not.fixed = Heatmap(glm.est1[genes.ori.MCM,], col = col, cluster_rows = mhclust.not.fixed,
              row_dend_gp = gpar(col = "gray50"),
              cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 11),
              show_row_names = F, show_column_names = F, show_column_dend = FALSE, show_row_dend = F, 
              column_title_gp = gpar(fontsize=14), column_title = 'GLM mean estimate',
              border = "gray20", row_title_rot = 0, 
              row_title = paste(length(genes.ori.MCM), "\n genes"),
              row_dend_width = unit(15, "mm"), use_raster = F,
              width = unit(60,'mm'), height = unit(130, 'mm'),
              show_heatmap_legend = F)
ht.mean.estimate.fixed = Heatmap(glm.est1[genes.alter.MCM,], col = col, cluster_rows = mhclust.fixed,
                                 row_dend_gp = gpar(col = "gray50"),
                                 cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 11),
                                 show_row_names = F, show_column_names = F, show_column_dend = FALSE, show_row_dend = F, 
                                 column_title_gp = gpar(fontsize=14), 
                                 border = "gray20", row_title_rot = 0, 
                                 row_title = paste("Altered models\n", length(genes.alter.MCM), " genes"),
                                 row_dend_width = unit(15, "mm"), use_raster = F,
                                 width = unit(60,'mm'), height = unit(4, 'mm'),
                                 show_heatmap_legend = F, bottom_annotation = bot.anno)
# grab this heatmap plotting, used for merging plots
mean_estimate_hm = grid.grabExpr(draw(ht.mean.estimate.not.fixed %v% ht.mean.estimate.fixed)) 

#model fitting heatmaps
ht.model.not.fixed = Heatmap(mat.MCM[genes.ori.MCM,], col = col, cluster_rows = mhclust.not.fixed,
                                     row_dend_gp = gpar(col = "gray50"),
                                     cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 20),
                                     show_row_names = F, show_column_names = F, show_column_dend = FALSE, show_row_dend = F, 
                                     column_title_gp = gpar(fontsize=14), column_title = 'MCM fitted',
                                     border = "gray20", row_title_rot = 0, 
                                     row_dend_width = unit(15, "mm"), use_raster = F,
                                     width = unit(60,'mm'), height = unit(130, 'mm'),
                                     show_heatmap_legend = F)
ht.model.fixed = Heatmap(mat.MCM[genes.alter.MCM,], col = col, cluster_rows = mhclust.fixed,
                             row_dend_gp = gpar(col = "gray50"),
                             cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 14),
                             show_row_names = F, show_column_names = F, show_column_dend = FALSE, show_row_dend = F, 
                             column_title_gp = gpar(fontsize=14), 
                             border = "gray20", row_title_rot = 0, 
                            
                             row_dend_width = unit(15, "mm"), use_raster = F,
                             width = unit(60,'mm'), height = unit(4, 'mm'),
                             show_heatmap_legend = F,bottom_annotation = bot.anno)
# grab this heatmap plotting, used for merging plots
model_hm = grid.grabExpr(draw(ht.model.not.fixed %v% ht.model.fixed)) 

#residual heatmaps
ht.resi.not.fixed = Heatmap(mat.disc[genes.ori.MCM,], col = col, cluster_rows = mhclust.not.fixed,
                             row_dend_gp = gpar(col = "gray50"),
                             cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 14),
                             show_row_names = F, show_column_names = F, show_column_dend = FALSE, show_row_dend = F, 
                             column_title_gp = gpar(fontsize=14), 
                             border = "gray20", row_title_rot = 0, column_title = 'Discrepancy',
                             row_dend_width = unit(15, "mm"), use_raster = F,
                             width = unit(60,'mm'), height = unit(130, 'mm'),
                             show_heatmap_legend = F)
ht.resi.fixed = Heatmap(mat.disc[genes.alter.MCM,], col = col, cluster_rows = mhclust.fixed,
                         row_dend_gp = gpar(col = "gray50"),
                         cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 14),
                         show_row_names = F, show_column_names = F, show_column_dend = FALSE, show_row_dend = F, 
                         column_title_gp = gpar(fontsize=14), 
                         border = "gray20", row_title_rot = 0, 
                         row_dend_width = unit(15, "mm"), use_raster = F,
                         width = unit(60,'mm'), height = unit(4, 'mm'),
                         show_heatmap_legend = F, bottom_annotation = bot.anno)
# grab this heatmap plotting, used for merging plots
residual_hm = grid.grabExpr(draw(ht.resi.not.fixed %v% ht.resi.fixed)) 

#synthetic heatmaps
bot_anno_synthetic = HeatmapAnnotation(foo = anno_text(colnames(cbind(mat.first, mat.second)), rot = 0, 
                                       just = 'center',gp = gpar(fontsize = 11), location = unit(1,'mm')),
                       show_annotation_name = F)

ht.synthetic.not.fixed = Heatmap(cbind(mat.first, mat.second)[genes.ori.MCM,], col = col, cluster_rows = mhclust.not.fixed,
                            row_dend_gp = gpar(col = "gray50"),
                            cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 14),
                            show_row_names = F, show_column_names = F, show_column_dend = FALSE, 
                            show_row_dend = T, row_dend_side = 'right',
                            column_title_gp = gpar(fontsize=13), 
                            border = "gray20", row_title_rot = 0, 
                            column_split = rep(c("First-peak response","Second-peak response"),each=7),
                            
                            row_dend_width = unit(15, "mm"), use_raster = F,
                            width = unit(95,'mm'), height = unit(130, 'mm'),
                            show_heatmap_legend = F)
ht.synthetic.fixed = Heatmap(cbind(mat.first, mat.second)[genes.alter.MCM,], col = col, cluster_rows = mhclust.fixed,
                        row_dend_gp = gpar(col = "gray50"),
                        cluster_columns = FALSE, column_gap = unit(1,"mm"), row_title_gp = gpar(fontsize = 14),
                        show_row_names = F, show_column_names = F, show_column_dend = FALSE, 
                        show_row_dend = T, row_dend_side = 'right',
                        column_title_gp = gpar(fontsize=13), 
                        border = "gray20", row_title_rot = 0, 
                        column_split = rep(c("First-peak response","Second-peak response"),each=7),
              
                        row_dend_width = unit(15, "mm"), use_raster = F,
                        width = unit(95,'mm'), height = unit(4, 'mm'),
                        show_heatmap_legend = F, bottom_annotation = bot_anno_synthetic)
# legend for the synthetic profile
lgd = Legend( col_fun = col, title = expression("log"[2]*"(FC)"),legend_height = unit(30,"mm"),grid_width = unit(4,"mm"),
              title_gp = gpar(fontsize = 11), labels_gp = gpar(fontsize = 10),title_gap = unit(4,"mm"))
# grab this heatmap plotting, used for merging plots
synthetic_hm = grid.grabExpr(draw(ht.synthetic.not.fixed %v% ht.synthetic.fixed, 
                                  annotation_legend_list = lgd)) 

# layout matrix indicating how to organize the heatmaps in a page
lay = rbind(c(1,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,4,4,4),c(1,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,4,4,4))

# for below, change the output directory as you need
jpeg('./data/figures/Fig3_r3.jpeg',width = 420, height = 170, unit = 'mm',res = 500)
grid.arrange(mean_estimate_hm,model_hm,residual_hm,synthetic_hm,layout_matrix = lay)
grid.text('Time (hpi)', x = unit(150,'mm'),y = unit(5,'mm'),gp = gpar(fontface = 'bold', fontsize=12))
grid.text('Time (hpi)', x = unit(330,'mm'),y = unit(5,'mm'),gp = gpar(fontface = 'bold', fontsize=12))
grid.text('-', x = unit(106,'mm'),y = unit(78,'mm'),gp = gpar(fontsize=55, col='gray30'))
grid.text('=', x = unit(190,'mm'),y = unit(78,'mm'),gp = gpar(fontsize=55, col='gray30'))
grid.text('A', x = unit(12,'mm'),y = unit(158,'mm'),gp = gpar(fontsize=21,fontface = 'bold'))
grid.text('B', x = unit(277,'mm'),y = unit(158,'mm'),gp = gpar(fontsize=21,fontface = 'bold'))
dev.off()

##########
### Fig S6 correlation between MCM and glm
cor.ori.g = sapply(genes.ori.MCM, function(x) {
  cor(glm.est1[x,], mat.MCM[x, ])
})
cor.alt.g = sapply(genes.alter.MCM, function(x) {
  cor(glm.est1[x,], mat.MCM[x, ])
})
cor.all.g = c(cor.ori.g, cor.alt.g)
hist(cor.all.g, breaks=100)
abline(v=median(cor.all.g), col='red', lty=2, lwd=2)
text(0.92,300, paste0('Median = ', round(median(cor.all.g), 2)), col='red', pos=2 )

jpeg("./data/figures/FigS6.corr.MCM.GLM.r3.jpeg",
     width = 220, height = 150, unit = "mm",res = 400)
opar = par(mar = c(5,5,2,4))
hist(cor.all.g, breaks = 100, xlab = "PCC between GLM-NB means and MCM fitted",
     ylab = "Number of genes", main = NA,
     col = 'gray80',border = "gray20",cex.lab = 1.8, cex.axis = 1.8,cex.main = 2,
     ylim = c(0,360), xlim = c(-0.5, 1.2))
abline(v = median(cor.all.g),lty = 5,lwd = 2,col = "red")
text(0.92,300, paste0('Median = ', round(median(cor.all.g), 2)), col='red', pos=2 )
par(opar)
dev.off()
